name: Check Links

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.3.2
        with:
          args: --verbose --exclude 'file*' --exclude-mail --no-progress './**/*.md'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}